# Generated by Django 6.0.7 on 2026-07-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('designation', models.CharField(max_length=200, null=True)),
                ('picture', models.ImageField(null=True, upload_to='static/team/')),
            ],
        ),
        migrations.RenameModel(
            old_name='gallery',
            new_name='tblgallery',
        ),
    ]
