# Generated by Django 6.0.7 on 2026-07-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_tblteam_rename_gallery_tblgallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblgallery',
            name='picture',
            field=models.ImageField(null=True, upload_to='static/picture/'),
        ),
    ]
