# Generated by Django 6.0.7 on 2026-07-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_tblgallery_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_register',
            fields=[
                ('name', models.CharField(max_length=50, null=True)),
                ('mobile', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50, null=True)),
                ('address', models.TextField(null=True)),
                ('profile_pic', models.ImageField(null=True, upload_to='static/profile/')),
            ],
        ),
    ]
