# Generated by Django 6.0.7 on 2026-07-30 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_tbl_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50, null=True)),
                ('pid', models.CharField(max_length=50, null=True)),
                ('product_name', models.CharField(max_length=80, null=True)),
                ('product_picture', models.CharField(max_length=500, null=True)),
                ('product_price', models.FloatField(null=True)),
                ('discount_price', models.FloatField(null=True)),
                ('product_quantity', models.IntegerField(null=True)),
                ('product_weight', models.CharField(null=True)),
                ('total_price', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=80, null=True)),
                ('category_picture', models.ImageField(null=True, upload_to='static/category/')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50, null=True)),
                ('pid', models.CharField(max_length=50, null=True)),
                ('product_name', models.CharField(max_length=80, null=True)),
                ('product_picture', models.CharField(max_length=500, null=True)),
                ('product_price', models.FloatField(null=True)),
                ('discount_price', models.FloatField(null=True)),
                ('product_quantity', models.IntegerField(null=True)),
                ('product_weight', models.CharField(null=True)),
                ('total_price', models.FloatField(null=True)),
                ('status', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=80, null=True)),
                ('product_price', models.FloatField(null=True)),
                ('product_quantity', models.IntegerField(null=True)),
                ('product_discount', models.FloatField(null=True)),
                ('product_description', models.TextField(null=True)),
                ('product_weight', models.CharField(null=True)),
                ('product_picture', models.ImageField(null=True, upload_to='static/product/')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.tbl_category')),
            ],
        ),
    ]
