# Generated by Django 6.0.7 on 2026-07-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_tbl_cart_tbl_category_tbl_order_tbl_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_product',
            name='product_quantity',
        ),
        migrations.AddField(
            model_name='tbl_order',
            name='order_date',
            field=models.DateField(null=True),
        ),
    ]
