# Generated by Django 6.0.7 on 2026-07-31 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_tbl_product_product_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_cart',
            name='discount_price',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
