# Generated by Django 6.0.7 on 2026-08-01 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_tbl_cart_discount_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_order_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50, null=True)),
                ('orderid', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('mobile', models.CharField(max_length=15, null=True)),
                ('address', models.TextField(null=True)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('total_amount', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_order_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=80, null=True)),
                ('product_picture', models.CharField(max_length=500, null=True)),
                ('product_price', models.FloatField(null=True)),
                ('discount_price', models.CharField(max_length=50, null=True)),
                ('product_quantity', models.IntegerField(null=True)),
                ('product_weight', models.CharField(null=True)),
                ('total_price', models.FloatField(null=True)),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tbl_order_info')),
            ],
        ),
    ]
