# Generated by Django 6.0.7 on 2026-08-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_tbl_order_info_tbl_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_order_info',
            name='order_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
