# Generated by Django 6.0.7 on 2026-08-15 04:41

from django.db import migrations

def clean_image_paths(apps, schema_editor):
    """
    Iterates through all image fields in relevant models and removes
    the 'static/' prefix if it exists in the stored path.
    """
    tbl_product = apps.get_model('user', 'tbl_product')
    tbl_category = apps.get_model('user', 'tbl_category')
    tblgallery = apps.get_model('user', 'tblgallery')
    tblteam = apps.get_model('user', 'tblteam')
    tbl_register = apps.get_model('user', 'tbl_register')

    # Clean tbl_product
    for obj in tbl_product.objects.all():
        if obj.product_picture and obj.product_picture.name.startswith('static/'):
            obj.product_picture.name = obj.product_picture.name.replace('static/', '', 1)
            obj.save()

    # Clean tbl_category
    for obj in tbl_category.objects.all():
        if obj.category_picture and obj.category_picture.name.startswith('static/'):
            obj.category_picture.name = obj.category_picture.name.replace('static/', '', 1)
            obj.save()

    # Clean tblgallery
    for obj in tblgallery.objects.all():
        if obj.picture and obj.picture.name.startswith('static/'):
            obj.picture.name = obj.picture.name.replace('static/', '', 1)
            obj.save()

    # Clean tblteam
    for obj in tblteam.objects.all():
        if obj.picture and obj.picture.name.startswith('static/'):
            obj.picture.name = obj.picture.name.replace('static/', '', 1)
            obj.save()

    # Clean tbl_register (profile_pic)
    for obj in tbl_register.objects.all():
        if obj.profile_pic and obj.profile_pic.name.startswith('static/'):
            obj.profile_pic.name = obj.profile_pic.name.replace('static/', '', 1)
            obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_tbl_order_info_order_date'), # Corrected dependency
    ]

    operations = [
        migrations.RunPython(clean_image_paths),
    ]