# Generated by Django 6.1 on 2026-08-15 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '000X_clean_image_paths'),
        ('user', '0010_clean_image_paths'),
    ]

    operations = [
    ]
